// src/views/Home/TopAnimeIsland/TopAnimeIsland.tsx
import { query_client } from "@solid/tan_stack_query/query_client";
import { QueryClientProvider } from "@tanstack/solid-query";
import { SolidQueryDevtools } from "@tanstack/solid-query-devtools";
import TopAnime from "./TopAnime/TopAnime";

export default function TopAnimeIsland() {
  return (
    <QueryClientProvider client={query_client}>
      <TopAnime />
      <SolidQueryDevtools />
    </QueryClientProvider>
  );
}

// src/views/Home/TopAnimeIsland/TopAnimeIsland.svelte
<script lang="ts">
  import { QueryClientProvider } from "@tanstack/svelte-query";
  import TopAnime from "./TopAnime/TopAnime.svelte";
  import { query_client } from "@svelte/tan_stack_query/query_client";
  import { SvelteQueryDevtools } from "@tanstack/svelte-query-devtools";
</script>

<QueryClientProvider client={query_client}>
  <TopAnime />
  <SvelteQueryDevtools />
</QueryClientProvider>
