// src/solid/components/buttons/Btn/Btn.tsx
import css from "./Btn.module.css";
import Cross from "@solid/icons/Cross";
import { cls } from "@utils/cls";
import type { JSX } from "solid-js";
import { splitProps } from "solid-js";

export default function Btn(props: Props) {
  const [p, rest] = splitProps(props, ["class", "children", "is_loading", "is_err", "disabled"]);

  return (
    <button {...rest} class={cls([css.btn, p.class])} disabled={p.disabled || p.is_loading}>
      {!p.is_loading && p.children}

      {p.is_loading && <div class={css.loading}></div>}

      {p.is_err && !p.is_loading && !p.disabled && <Cross class={css.err} />}
    </button>
  );
}

interface Props extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  is_loading?: boolean;
  is_err?: boolean;
}

// src/svelte/components/buttons/Btn/Btn.svelte
<script lang="ts">
  import Cross from "@svelte/components/icons/Cross.svelte";
  import css from "./Btn.module.css";
  import type { HTMLButtonAttributes } from "svelte/elements";

  type Props = HTMLButtonAttributes & {
    is_loading?: boolean;
    is_err?: boolean;
    class?: string;
  };

  const { is_loading, is_err, class: cls, children, ...rest }: Props = $props();
</script>

<button class={[css.btn, cls]} disabled={rest.disabled || is_loading} {...rest}>
  {#if is_loading}
    <div class={[css.loading]}></div>
  {:else if is_err && !is_loading}
    <Cross class={css.err} />
  {:else}
    {@render children?.()}
  {/if}
</button>
