// src/svelte/components/inputs/Search/Search.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from "svelte/elements";
  import css from "./Search.module.css";
  import { onMount } from "svelte";
  import Loading from "@svelte/components/icons/Loading.svelte";
  import Success from "@svelte/components/icons/Success.svelte";

  type Props = HTMLInputAttributes & {
    err?: string;
    is_loading?: boolean;
    is_success?: boolean;
    on_search?: (txt: string) => void;
  };

  let {
    err,
    on_search,
    is_loading,
    is_success,
    class: cls,
    placeholder = "Buscar",
    ...rest
  }: Props = $props();
  let input_ref: HTMLInputElement;

  onMount(() => {
    input_ref.focus();
  });

  function handle_enter(event: KeyboardEvent) {
    if (!on_search) return;
    if (event.key === "Enter") {
      on_search(input_ref.value);
    }
  }

  function handle_click() {
    if (!on_search) return;
    if (input_ref) {
      on_search(input_ref.value);
    }
  }
</script>

<label class={[css.search, cls]}>
  <input
    bind:this={input_ref}
    {...rest}
    type="text"
    class={[err && css.input_err]}
    title={err}
    {placeholder}
    onkeydown={handle_enter}
  />
  {#if is_loading}
    <Loading class={css.loading} />
  {:else if is_success}
    <Success class={css.success} />
  {:else}
    <button class={css.lupe} onclick={handle_click}>🔍️</button>
  {/if}
</label>

// src/react/components/inputs/Search/Search.tsx
import React, { useEffect, useRef } from "react";
import css from "./Search.module.css";
import { cls } from "@utils/cls";
import Loading from "@react/components/icons/Loading";
import Success from "@react/components/icons/Success";

type Props = React.InputHTMLAttributes<HTMLInputElement> & {
  err?: string;
  is_loading?: boolean;
  is_success?: boolean;
};

export default function Search(props: Props) {
  const { err, is_loading, is_success, className, placeholder = "Buscar", ...rest } = props;

  const input_ref = useRef<HTMLInputElement>(null);

  useEffect(() => {
    input_ref.current?.focus();
  }, []);

  return (
    <label className={cls([css.search, className])}>
      <input
        {...rest}
        ref={input_ref}
        type="text"
        className={cls([err && css.input_err])}
        title={err}
        placeholder={placeholder}
      />

      {is_loading && <Loading className={css.loading} />}
      {is_success && <Success className={css.success} />}
    </label>
  );
}
