// src/react/components/shared/LiteYoutube/LiteYoutube.tsx
import "@justinribeiro/lite-youtube";
import css from "./LiteYoutube.module.css";
import { cls } from "@utils/cls";
import Play from "@react/components/icons/Play";
import { useEffect, useRef, type HTMLAttributes } from "react";
import type { LiteYTEmbed } from "@justinribeiro/lite-youtube";

export default function LiteYoutube(props: Props) {
  const { videoid, className, ...rest } = props;
  const lite = useRef<LiteYTEmbed>(null);

  useEffect(() => {
    if (!lite.current) return;

    const handle_lite = () => {
      lite.current?.setAttribute("style", "opacity:1;");
    };

    lite.current.addEventListener("liteYoutubeIframeLoaded", handle_lite);

    return () => {
      lite.current?.removeEventListener("some-event", handle_lite);
    };
  });

  return (
    <div className={cls([css.lite, className])} {...rest}>
      <Play className={css.shadow} />
      {/* @ts-ignore */}
      <lite-youtube ref={lite} videoid={videoid || "mqDg5Oi8S_E"}></lite-youtube>
    </div>
  );
}

type Props = HTMLAttributes<HTMLDivElement> & {
  videoid: string;
};

// src/svelte/components/shared/LiteYoutube/LiteYoutube.svelte
<script lang="ts">
  import Play from "@svelte/components/icons/Play.svelte";
  import css from "./LiteYoutube.module.css";
  import "@justinribeiro/lite-youtube";
  import type { HTMLAttributes } from "svelte/elements";
  import { onMount, onDestroy } from "svelte";

  type Props = HTMLAttributes<HTMLDivElement> & {
    videoid: string;
  };

  const { videoid, class: cls, ...rest }: Props = $props();
  let play: any;
  let lite: HTMLElement;

  const handle_lite = () => {
    lite.style.opacity = "1";
    play.style.backgroundColor = "transparent";
  };

  onMount(() => lite.addEventListener("liteYoutubeIframeLoaded", handle_lite));

  onDestroy(() => lite.addEventListener("liteYoutubeIframeLoaded", handle_lite));
</script>

<div class={[css.lite, cls]} {...rest}>
  <Play bind:this={play} class={css.shadow} />
  <lite-youtube bind:this={lite} class={css.lite} {videoid}></lite-youtube>
</div>
