// src/react/components/shared/SearchAnimesIsland/SearchAnimes/SearchAnimes.tsx
import Cross from "@react/components/icons/Cross";
import css from "./SearchAnimes.module.css";
import Search from "@react/components/inputs/Search/Search";
import { useStore } from "@nanostores/react";
import { search_animes_store } from "./search_animes_store";
import Btn from "@react/components/buttons/Btn/Btn";

export default function SearchAnimes() {
  const { is_visible } = useStore(search_animes_store.store);

  if (!is_visible) return null;
  return (
    <div className={css.search}>
      <form
        className={css.form}
        onSubmit={(e) => {
          e.preventDefault();
          console.log("submit");
          console.log(e.target);
        }}
      >
        <Cross className={css.cross} onClick={search_animes_store.toggle_visible} />
        <Search />
        <Btn>Buscar</Btn>
      </form>
    </div>
  );
}

// src/svelte/components/shared/SearchAnimes/SearchAnimes.svelte
<script lang="ts">
  import Search from "@svelte/components/inputs/Search/Search.svelte";
  import css from "./SearchAnimes.module.css";
  import {
    search_animes_store,
    search_animes_store_toggle_is_visible,
  } from "./search_animes_store";
  import Cross from "@svelte/components/icons/Cross.svelte";

  const is_visible = $derived($search_animes_store.is_visible);
</script>

{#if is_visible}
  <div class={[css.search]}>
    <div class={css.wrapper}>
      <Cross class={css.cross} onclick={search_animes_store_toggle_is_visible} />
      <Search placeholder="Buscar" />
    </div>
  </div>
{/if}
