// src/react/components/buttons/Btn/Btn.tsx
import { cls } from "@utils/cls";
import css from "./Btn.module.css";
import Cross from "@react/components/icons/Cross";
import Loading from "@react/components/icons/Loading";

export default function Btn(props: Props) {
  const { className, children, loading, err, disabled, ...rest } = props;

  return (
    <button {...rest} className={cls([css.btn, className])} disabled={disabled || loading}>
      {loading && <Loading width={20} height={20} />}
      {err && !loading && !disabled && <Cross className={css.err} width={20} height={20} />}
      {!loading && children}
    </button>
  );
}

type Props = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  loading?: boolean;
  err?: boolean;
};

// src/solid/components/buttons/Btn/Btn.tsx
import css from "./Btn.module.css";
import Cross from "@solid/icons/Cross";
import { cls } from "@utils/cls";
import type { JSX } from "solid-js";
import { splitProps } from "solid-js";

export default function Btn(props: Props) {
  const [p, rest] = splitProps(props, ["class", "children", "is_loading", "is_err", "disabled"]);

  return (
    <button {...rest} class={cls([css.btn, p.class])} disabled={p.disabled || p.is_loading}>
      {!p.is_loading && p.children}

      {p.is_loading && <div class={css.loading}></div>}

      {p.is_err && !p.is_loading && !p.disabled && <Cross class={css.err} />}
    </button>
  );
}

interface Props extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  is_loading?: boolean;
  is_err?: boolean;
}
