// src/views/AnimeView/AnimeIsland/AnimeIsland.tsx
import { QueryClientProvider } from "@tanstack/react-query";
import { query_client } from "@react/tan_stack_query/query_client";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Anime from "./Anime/Anime";

export default function AnimeIsland() {
  return (
    <QueryClientProvider client={query_client}>
      <Anime />
      <ReactQueryDevtools />
    </QueryClientProvider>
  );
}

// src/views/Anime/AnimeIsland/AnimeIsland.svelte
<script lang="ts">
  import { QueryClientProvider } from "@tanstack/svelte-query";
  import { query_client } from "@svelte/tan_stack_query/query_client";
  import { SvelteQueryDevtools } from "@tanstack/svelte-query-devtools";
  import AnimeById from "./AnimeById/AnimeById.svelte";
</script>

<QueryClientProvider client={query_client}>
  <AnimeById />
  <SvelteQueryDevtools />
</QueryClientProvider>
