// src/views/Anime/AnimeIsland/AnimeIsland.svelte
<script lang="ts">
  import { QueryClientProvider } from "@tanstack/svelte-query";
  import { query_client } from "@svelte/tan_stack_query/query_client";
  import { SvelteQueryDevtools } from "@tanstack/svelte-query-devtools";
  import AnimeById from "./AnimeById/AnimeById.svelte";
</script>

<QueryClientProvider client={query_client}>
  <AnimeById />
  <SvelteQueryDevtools />
</QueryClientProvider>

// src/views/Anime/AnimeIsland/AnimeIsland.tsx
import { query_client } from "@solid/tan_stack_query/query_client";
import { QueryClientProvider } from "@tanstack/solid-query";
import { SolidQueryDevtools } from "@tanstack/solid-query-devtools";
import AnimeById from "./AnimeById/AnimeById";

export default function AnimeIsland() {
  return (
    <QueryClientProvider client={query_client}>
      <AnimeById />
      <SolidQueryDevtools />
    </QueryClientProvider>
  );
}
